### ISSUE TITLE
Error with Template Variables in JSON Input

### ISSUE THREAD

**Issue by jrpedrianes** [TotalTechGeek/handlebars-jle#2]
Hi,

I’m running into an issue when trying to use a simple JSON input with a template. Here’s the situation:

My JSON input is:

```json
{  
  "ELEMENT_001": "Pizza"  
}
```

And my template is:

```markdown
Today I choose {{ELEMENT_001}}  
```
When I compile this template, I get the following error:

```
Error: Method 'ELEMENT_00' was not found in the Logic Engine.  
```

It seems like the variable name is being incorrectly truncated during the compilation process, as the error refers to `ELEMENT_00` instead of the full key `ELEMENT_001`.

Could you help me understand:

* Is this a bug in how variables are processed?
* Is there any workaround to make this work correctly?

Thanks for your support, and let me know if you need more information!

Greetings

**Comment by TotalTechGeek** [comment]
Ah man, it was a really obvious issue:

I accidentally wrote: `[@$a-zA-Z_.-0-9]` instead of `[@$a-zA-Z_.0-9-]`

I'll add some tests and push this guy out

**Comment by TotalTechGeek** [comment]
New version `0.0.22` has been pushed; a small test has been added to check for this. 

My tests weren't checking correctly for numbers in the variable names 🙃

**Comment by jrpedrianes** [comment]
:joy: Something similar happened to me not long ago.

I just tested and it works perfectly. 

Thank you for your quick response
